// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'postalDetail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PostalDetail _$PostalDetailFromJson(Map<String, dynamic> json) => PostalDetail(
      json['fr_address'] as String?,
      json['det_county'] as String?,
      json['pay_amount'] as String?,
      json['fr_tel'] as String?,
      json['cod_amount'] as String?,
      json['fr_postcode'] as String?,
      json['dimension'] as String?,
      json['service_items'] as String?,
      json['det_name'] as String?,
      json['det_address'] as String?,
      json['cod_account'] as String?,
      json['det_moo'] as String?,
      json['app'] as String?,
      json['tracking'] as String?,
      json['fr_district'] as String?,
      json['fr_country_iso'] as String?,
      json['price'] as String?,
      json['merchant'] as String?,
      json['weight'] as String?,
      json['sta'] as String?,
      json['det_district'] as String?,
      json['itm'] as String?,
      json['itm_sku'] as String?,
      json['fr_county'] as String?,
      json['det_country_iso'] as String?,
      json['fr_gps'] as String?,
      json['pay_id'] as String?,
      json['det_tel'] as String?,
      json['serv'] as String?,
      json['log'] as String?,
      json['fr_province'] as String?,
      json['fr_name'] as String?,
      json['fr_moo'] as String?,
      json['det_province'] as String?,
      json['det_gps'] as String?,
      json['det_postcode'] as String?,
      json['distance'] as String?,
    );

Map<String, dynamic> _$PostalDetailToJson(PostalDetail instance) =>
    <String, dynamic>{
      'fr_address': instance.fr_address,
      'det_county': instance.det_county,
      'pay_amount': instance.pay_amount,
      'fr_tel': instance.fr_tel,
      'cod_amount': instance.cod_amount,
      'fr_postcode': instance.fr_postcode,
      'dimension': instance.dimension,
      'service_items': instance.service_items,
      'det_name': instance.det_name,
      'det_address': instance.det_address,
      'cod_account': instance.cod_account,
      'det_moo': instance.det_moo,
      'app': instance.app,
      'tracking': instance.tracking,
      'fr_district': instance.fr_district,
      'fr_country_iso': instance.fr_country_iso,
      'price': instance.price,
      'merchant': instance.merchant,
      'weight': instance.weight,
      'sta': instance.sta,
      'det_district': instance.det_district,
      'itm': instance.itm,
      'itm_sku': instance.itm_sku,
      'fr_county': instance.fr_county,
      'det_country_iso': instance.det_country_iso,
      'fr_gps': instance.fr_gps,
      'pay_id': instance.pay_id,
      'det_tel': instance.det_tel,
      'serv': instance.serv,
      'log': instance.log,
      'fr_province': instance.fr_province,
      'fr_name': instance.fr_name,
      'fr_moo': instance.fr_moo,
      'det_province': instance.det_province,
      'det_gps': instance.det_gps,
      'det_postcode': instance.det_postcode,
      'distance': instance.distance,
    };
